In [4]:
import pandas as pd
from gensim.models import Word2Vec
from sklearn.metrics.pairwise import cosine_similarity


ingredients_df = pd.read_csv("last_ingredients.csv")
recipes_df = pd.read_csv("Final_recipe.csv")

In [5]:
# 'RecipeIngredient' 열의 재료 번호를 실제 재료 이름으로 변환

# 재료 번호와 실제 재료를 매핑
ingredient_map = ingredients_df.set_index('Index')['Ingredient'].to_dict()

# 각 레시피의 재료 번호를 재료 이름으로 변환하는 함수
def convert_ingredients(ingredient_list_str, ingredient_map):
    # 문자열을 리스트로 변환 (ex: '[32, 61, 9]' -> [32, 61, 9])
    ingredient_list = eval(ingredient_list_str)
    # 재료 번호를 재료 이름으로 변환
    return [ingredient_map.get(ingr_id, f'Unknown({ingr_id})') for ingr_id in ingredient_list]

# 레시피의 'RecipeIngredient'를 변환
recipes_df['ConvertedIngredients'] = recipes_df['RecipeIngredient'].apply(lambda x: convert_ingredients(x, ingredient_map))

# 변환된 데이터 확인
recipes_df[['name', 'RecipeIngredient', 'ConvertedIngredients']].head()

,name,RecipeIngredient,ConvertedIngredients
0,두부 구이 어묵 볶음 밥반찬 도시락 간단레시피,"[32, 61, 9, 58, 15, 3, 5, 12, 2]","[두부, 어묵, 대파, 멸치, 식용유, 설탕, 간장, 깨, 소금]"
1,[무알콜모히또 만드는 법]상큼한 라임에이드 논알콜 과일 음료,"[440, 477, 282, 138, 3]","[라임, 애플민트, 탄산수, 얼음, 설탕]"
2,건새우 고추장 볶음,"[181, 15, 16, 1, 7, 48, 3, 12]","[건새우, 식용유, 고추장, 마늘, 참기름, 물엿, 설탕, 깨]"
3,쭈꾸미볶음 레시피 간단한 양념장,"[275, 9, 4, 46, 80, 6, 13, 72, 10, 1, 20, 17, ...","[쭈꾸미, 대파, 양파, 양배추, 찹쌀, 물, 청양고추, 기름, 고춧가루, 마늘, ..."
4,삼삼칩스&인삼견과딥소스,"[248, 89, 57, 72, 2, 396, 205, 199, 351, 112, ...","[인삼, 튀김가루, 전분가루, 기름, 소금, 수삼, 아몬드, 잣, 두유, 포도씨유,..."

In [6]:
from gensim.models import Word2Vec
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Word2Vec 모델 학습을 위해 변환된 재료 리스트 추출
recipe_list = recipes_df['ConvertedIngredients'].tolist()

# Word2Vec 모델 학습
model = Word2Vec(sentences=recipe_list, vector_size=100, window=5, min_count=1, workers=4)

# 각 레시피를 벡터로 변환 (단어 벡터의 평균값 사용)
def get_recipe_vector(recipe, model):
    word_vectors = [model.wv[word] for word in recipe if word in model.wv]
    return np.mean(word_vectors, axis=0) if word_vectors else np.zeros(model.vector_size)

# 레시피 벡터 생성
recipe_vectors = {i: get_recipe_vector(ingredients, model) for i, ingredients in enumerate(recipe_list)}

# 레시피 간 유사도 계산 함수
def word2vec_content_based_recommendations(recipe_id, recipe_vectors, top_n=5):
    sim_scores = cosine_similarity([recipe_vectors[recipe_id]], list(recipe_vectors.values()))[0]
    sim_scores = list(enumerate(sim_scores))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:top_n+1]  # 가장 유사한 상위 n개의 레시피
    similar_recipe_ids = [i[0] for i in sim_scores]
    return similar_recipe_ids

# 레시피 0번과 유사한 레시피 추천
similar_recipes = word2vec_content_based_recommendations(0, recipe_vectors)
similar_recipe_info = recipes_df.loc[similar_recipes, :]

similar_recipe_info

,id,name,bestName,cookingTime,servings,difficulty,description,by_sort,by_ingredient,by_situation,image1,image2,RecipeIngredient,top_3_per_menu,ConvertedIngredients
67681,6942348,"백파더 어묵볶음,어묵탕 초간단하게 만드는 법",어묵탕,30,2,아무나,요즘 백파더 인기가 아주 좋죠? 어제 방송에서는 백파더의 초간단한 어묵요리가 나왔...,국/탕,가공식품류,일상,https://recipe1.ezmember.co.kr/cache/recipe/20...,https://recipe1.ezmember.co.kr/cache/recipe/20...,"[61, 4, 9, 13, 5, 3, 15, 1, 6, 7, 12, 58, 61, ...","[61, 9, 30]","[어묵, 양파, 대파, 청양고추, 간장, 설탕, 식용유, 마늘, 물, 참기름, 깨,..."
14274,6777696,어묵 잔치국수 끓이기,어묵잔치국수,30,2,초급,고명 푸짐하게 올린 잔치 국수입니다.,면/만두,가공식품류,일상,https://recipe1.ezmember.co.kr/cache/recipe/20...,https://recipe1.ezmember.co.kr/cache/recipe/20...,"[58, 45, 6, 61, 87, 14, 4, 72, 144, 5, 24, 52,...","[61, 144, 9]","[멸치, 다시마, 물, 어묵, 피망, 당근, 양파, 기름, 소면, 간장, 국간장, ..."
11329,6972442,도시락반찬/밑반찬/아이반찬/ 백종원 간장어묵볶음 만드는법,간장어묵볶음,15,4,초급,아이들 겨울 방학이 시작되니 본격 삼식이모드로 돌입했어요. 냉장고가 꽉꽉 차있어야 ...,밑반찬,가공식품류,일상,https://recipe1.ezmember.co.kr/cache/recipe/20...,https://recipe1.ezmember.co.kr/cache/recipe/20...,"[61, 4, 5, 15, 9, 6, 12]","[61, 5, 4]","[어묵, 양파, 간장, 식용유, 대파, 물, 깨]"
73085,6947305,백파더어묵탕 5분이면 돼,어묵탕,5,1,아무나,지금같이 뜨끈한 국물이 생각나는 날씨에는 백파더어묵탕 정말 딱인데요 이제는 쌀쌀하다...,국/탕,가공식품류,초스피드,https://recipe1.ezmember.co.kr/cache/recipe/20...,https://recipe1.ezmember.co.kr/cache/recipe/20...,"[61, 6, 58, 4, 9, 5, 3, 1, 17]","[61, 9, 30]","[어묵, 물, 멸치, 양파, 대파, 간장, 설탕, 마늘, 맛술]"
42480,6993166,간단한 어묵탕 만들기!,어묵탕,20,2,아무나,짧은시간 안에 간단한 재료들로 어묵탕을 만들어요 나무젓가락에 지그재그로 꽂아서 포장...,국/탕,가공식품류,초스피드,https://recipe1.ezmember.co.kr/cache/recipe/20...,https://recipe1.ezmember.co.kr/cache/recipe/20...,"[61, 6, 58, 4, 9, 5, 3, 1, 17, 177]","[61, 9, 30]","[어묵, 물, 멸치, 양파, 대파, 간장, 설탕, 마늘, 맛술, 다시다]"

In [7]:
from gensim.models import Word2Vec
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Word2Vec 모델 학습을 위해 변환된 재료 리스트 추출
recipe_list = recipes_df['ConvertedIngredients'].tolist()

# Word2Vec 모델 학습
model = Word2Vec(sentences=recipe_list, vector_size=400, window=5, min_count=1, workers=4)

# 각 레시피를 벡터로 변환 (단어 벡터의 평균값 사용)
def get_recipe_vector(recipe, model):
    word_vectors = [model.wv[word] for word in recipe if word in model.wv]
    return np.mean(word_vectors, axis=0) if word_vectors else np.zeros(model.vector_size)

# 레시피 벡터 생성
recipe_vectors = {i: get_recipe_vector(ingredients, model) for i, ingredients in enumerate(recipe_list)}

# 사용자의 재료 리스트를 벡터로 변환
def get_user_vector(user_ingredients, model):
    return get_recipe_vector(user_ingredients, model)

# 레시피 간 유사도 계산 함수
def word2vec_content_based_recommendations(user_vector, recipe_vectors, top_n=5):
    sim_scores = cosine_similarity([user_vector], list(recipe_vectors.values()))[0]
    sim_scores = list(enumerate(sim_scores))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    similar_recipe_ids = [i[0] for i in sim_scores[:top_n]]  # 가장 유사한 상위 n개의 레시피
    return similar_recipe_ids

# 사용자가 가지고 있는 재료 리스트
user_ingredients = ['계란', '소금', '간장', '돼지고기', '소고기', '대파', '마늘', '양파']  # 사용자가 가지고 있는 재료 리스트 입력

# 사용자의 재료 리스트를 벡터로 변환
user_vector = get_user_vector(user_ingredients, model)

# 사용자 재료와 유사한 레시피 추천
similar_recipes = word2vec_content_based_recommendations(user_vector, recipe_vectors)
similar_recipe_info = recipes_df.loc[similar_recipes, ['id']]

similar_recipes

[65368, 59356, 75902, 64378, 71018]

In [5]:
model.save('word2vec_recipes.model')

In [6]:
vectors_file = 'recipe_vectors.json'

In [8]:
import json

In [9]:
import pandas as pd
df = pd.read_csv('Final_recipe.csv')

columns_to_select = ['id', 'RecipeIngredient', 'by_sort', 'by_situation']
df_selected = df[columns_to_select]
df_selected.to_csv('summary_recipe2.csv', index=False)

In [10]:
unique_sort = df_selected['by_sort'].unique().tolist()
unique_situation = df_selected['by_situation'].unique().tolist()

In [18]:
category_df = df_selected[df_selected['by_sort'] == '밑반찬']

In [19]:
category_df

,id,RecipeIngredient,by_sort,by_situation
0,6992711,"[32, 61, 9, 58, 15, 3, 5, 12, 2]",밑반찬,일상
2,6836645,"[181, 15, 16, 1, 7, 48, 3, 12]",밑반찬,일상
8,6942011,"[23, 10, 5, 18, 3, 19, 7, 12]",밑반찬,일상
14,6830251,"[32, 6, 23, 1, 93, 10]",밑반찬,일상
15,6920262,"[4, 5, 3, 18, 6, 70]",밑반찬,일상
...,...,...,...,...
90431,6913641,"[8, 4, 13, 9, 5, 6, 3, 19, 1]",밑반찬,일상
90437,6909826,"[58, 2, 15, 12, 10, 48, 1, 7]",밑반찬,일상
90439,6902462,"[61, 4, 9, 27, 93, 262, 1, 7, 12]",밑반찬,일상
90454,7005169,"[53, 4, 14, 9, 10, 5, 3, 43, 20, 1, 6, 104]",밑반찬,초스피드
90455,6915445,"[32, 42]",밑반찬,술안주

In [14]:
unique_situation

['일상',
 '손님접대',
 '간식',
 nan,
 '다이어트',
 '기타',
 '명절',
 '도시락',
 '술안주',
 '초스피드',
 '야식',
 '해장',
 '이유식',
 '푸드스타일링']

In [15]:
nan_count = df['by_situation'].isna().sum()

# 결과 출력
print(nan_count)

2632

In [12]:
import requests

url = "http://localhost:8000/recommend"
data = {
    "ingredients": ["계란", "소금", "간장"]
}

response = requests.post(url, json=data)

if response.status_code == 200:
    print("추천 레시피:", response.json())
else:
    print("오류 발생:", response.status_code, response.text)

추천 레시피: {'recommended_recipes': [5754584, 6949079, 6927390, 6973290, 6897469, 6955972, 6843298, 6959329, 6906702, 6903397, 6873716, 6894569, 6873849, 6855191, 6724969, 6796599, 6854191, 6859247, 6920883, 3358379, 6923049, 6892953, 6738275, 6896663, 7000003, 6903144, 6850255, 6885865, 6931174, 6984068, 6677545, 6831423, 6914227, 6996501, 6957336, 6861742, 6883282, 6965686, 6736270, 7019527, 6985986, 6993267, 6906715, 6942131, 6971857, 6956743, 6910057, 7012689, 7007856, 7003037]}

In [16]:
import openai
import time

# OpenAI API Key 설정
openai.api_key = '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'

# 재료 목록
ingredients = [
    'tomato', 'sesame oil'
    # 900개 재료 목록 추가
]

# 이미지 생성 함수
def generate_ingredient_icon(ingredient_name):
    prompt = f"{ingredient_name} image, vector illustration with simple flat design, black outline on white background, simple shapes, clipart sticker style, pastel colors, simple lines, flat color drawing, simple shapes, simple line drawing, png format, white background, png crop --ar 19:22"


    try:
        response = openai.Image.create(
            model="dall-e-3",
            prompt=prompt,
            n=1,
            size="1024x1024"  # 원하면 크기 조정 가능
        )
        # 생성된 이미지 URL 반환
        image_url = response['data'][0]['url']
        return image_url
    except Exception as e:
        print(f"Error generating image for {ingredient_name}: {e}")
        return None

# 모든 재료에 대해 아이콘 생성
def generate_icons_for_ingredients():
    icons = []
    
    for ingredient in ingredients:
        icon_url = generate_ingredient_icon(ingredient)
        if icon_url:
            icons.append({"ingredient": ingredient, "icon_url": icon_url})
        time.sleep(1)  # API 호출을 피하기 위한 시간 대기
    
    return icons

# 아이콘 생성
icons = generate_icons_for_ingredients()

# 결과 출력 (아이콘 URL 출력)
for icon in icons:
    print(f"{icon['ingredient']}: {icon['icon_url']}")

tomato: https://oaidalleapiprodscus.blob.core.windows.net/private/org-Gyk0FrFo9zq1gtm3HvCljaho/user-PfxoyA8yQQCTc1MoyTD8Oe53/img-6KQ1AMx6G8o710Om6CWh5M0V.png?st=2024-11-12T14%3A15%3A14Z&se=2024-11-12T16%3A15%3A14Z&sp=r&sv=2024-08-04&sr=b&rscd=inline&rsct=image/png&skoid=d505667d-d6c1-4a0a-bac7-5c84a87759f8&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2024-11-12T15%3A09%3A55Z&ske=2024-11-13T15%3A09%3A55Z&sks=b&skv=2024-08-04&sig=6xbE9mmmQrZN4dUSEh4ohNGHGf25Z0xU4BmV3mQcotc%3D
sesame oil: https://oaidalleapiprodscus.blob.core.windows.net/private/org-Gyk0FrFo9zq1gtm3HvCljaho/user-PfxoyA8yQQCTc1MoyTD8Oe53/img-hEY2m1WxQ7AboGKHBoNGgFeg.png?st=2024-11-12T14%3A15%3A28Z&se=2024-11-12T16%3A15%3A28Z&sp=r&sv=2024-08-04&sr=b&rscd=inline&rsct=image/png&skoid=d505667d-d6c1-4a0a-bac7-5c84a87759f8&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2024-11-11T15%3A22%3A26Z&ske=2024-11-12T15%3A22%3A26Z&sks=b&skv=2024-08-04&sig=2sqQw5hfvyrRgXJr8%2BxvhaoZi%2B79qE3YmlnVb%2BT7oC4%3D

In [ ]:
import openai

openai.api_key = ''

def generate_image(prompt, size="1024x1024"):
    response = openai.Image.create(
        prompt=prompt,
        n=1,
        size=size
    )
    image_url = response['data'][0]['url']
    return image_url

# 예시: 한국어로 재료 이미지 생성
prompt = "단순한 디자인의 토마토 아이콘"
image_url = generate_image(prompt)
print(image_url)

AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)